## ======================================================================
## Pipeline for GPDB PL/R GPPKG
## ======================================================================

groups:
- name: RELEASE
  jobs:
    - plr_centos6_release
    - plr_centos7_release
    - plr_suse11_release

resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

# Github Source Codes

- name: plr_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/plr.git

- name: release_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/plr.git
    tag_filter: 2.*

# centos 7

- name: plr_gpdb_centos7_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb5/plr/centos7/plr-devel.gppkg

- name: plr_gpdb_centos7_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb5/plr/plr-(.*)-rhel7-x86_64.gppkg

# centtos 6

- name: plr_gpdb_centos6_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb5/plr/centos6/plr-devel.gppkg

- name: plr_gpdb_centos6_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb5/plr/plr-(.*)-rhel6-x86_64.gppkg

# suse11

- name: plr_gpdb_suse11_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb5/plr/suse11/plr-devel.gppkg

- name: plr_gpdb_suse11_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb5/plr/plr-(.*)-sles11-x86_64.gppkg

## ======================================================================
## jobs
## ======================================================================
jobs:
- name: plr_centos6_release
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
    - get: plr_gpdb_centos6_build
    - get: release_src
      trigger: true
  - task: release_PLR
    file: plr_src/concourse/tasks/release_plr.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_plr: plr_gpdb_centos6_build
    output_mapping:
        plr_gppkg: plr_gpdb_centos6_release
    params:
      OSVER: centos6
      GPDBVER: gp5
  - put: plr_gpdb_centos6_release
    params:
      file: plr_gpdb_centos6_release/plr-*.gppkg

- name: plr_centos7_release
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
    - get: plr_gpdb_centos7_build
    - get: release_src
      trigger: true
  - task: release_PLR
    file: plr_src/concourse/tasks/release_plr.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_plr: plr_gpdb_centos7_build
    output_mapping:
      plr_gppkg: plr_gpdb_centos7_release
    params:
      OSVER: centos7
      GPDBVER: gp5
  - put: plr_gpdb_centos7_release
    params:
      file: plr_gpdb_centos7_release/plr-*.gppkg

- name: plr_suse11_release
  plan:
  - aggregate:
    - get: plr_src
    - get: plr_gpdb_suse11_build
    - get: release_src
      trigger: true
  - task: release_PLR
    file: plr_src/concourse/tasks/release_plr_sles.yml
    input_mapping:
      bin_plr: plr_gpdb_suse11_build
    output_mapping:
      plr_gppkg: plr_gpdb_suse11_release
    params:
      OSVER: suse11
      GPDBVER: gp5
  - put: plr_gpdb_suse11_release
    params:
      file: plr_gpdb_suse11_release/plr-*.gppkg

