---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: '11-beta'

inputs:
- name: plr_src

outputs:
- name: bin_r

run:
  path: plr_src/concourse/scripts/build_r.sh

params:
  OSVER:
