---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: '11-beta'

inputs:
- name: bin_gpdb
- name: plr_src
- name: bin_r
- name: gpdb_src

outputs:
- name: bin_plr

run:
  path: plr_src/concourse/scripts/build_plr.sh

params:
  OSVER:
  GPDBVER:
