platform: linux
image_resource:
  type: docker-image
inputs:
  - name: plr_src
  - name: xz
  - name: zlib
  - name: bzip2

outputs:
  - name: bin_r

run:
  path: plr_src/concourse/scripts/build_r.sh
params:
  OSVER:
