---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/sles-gpdb-dev
    tag: '11-beta'

inputs:
- name: plr_src
- name: bin_plr

outputs:
  - name: plr_gppkg

run:
  path: plr_src/concourse/scripts/release_plr.sh

params:
  OSVER:
  GPDBVER:
